services:
  market-place:
    image: market-place:latest
    environment:
      SPRING_MAIL_HOST: smtp.mail.ru
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: prodmarketplace@mail.ru
      SPRING_MAIL_PASSWORD: VBTxyZzG9EWAHdpMsAat
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
      SERVER_SERVLET_ENCODING_CHARSET: UTF-8
      SERVER_SERVLET_ENCODING_ENABLED: true
      SERVER_SERVLET_ENCODING_FORCE: true

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
