version: '3.8'
services:
  market-place:
    image: market-place:latest
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
    restart: "no"
    ports:
      - "8080:8080"
    environment:
      SPRING_MAIL_HOST: smtp.mail.ru
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: prodmarketplace@mail.ru
      SPRING_MAIL_PASSWORD: VBTxyZzG9EWAHdpMsAat
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
      SERVER_SERVLET_ENCODING_CHARSET: UTF-8
      SERVER_SERVLET_ENCODING_ENABLED: true
      SERVER_SERVLET_ENCODING_FORCE: true

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"  # Порт для отправки писем
      - "8025:8025"  # Веб-интерфейс Mailhog

  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - URL=4894777-zw28304.twc1.net
      - EMAIL=oleg_novak_98@mail.ru
      - WEBROOT=/certbot
      - NGINX_CONTAINER=nginx
      - SERVER_CONTAINER_LABEL=nginx
    volumes:
      - ./certs:/etc/letsencrypt
      - ./data:/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - ./nginx.conf:/etc/nginx/nginx.conf
    labels:
      - "letsencrypt.handle=true"
    restart: unless-stopped

volumes:
  certs:
  data:
